version = 1

[[analyzers]]
name = "python"

  [analyzers.meta]
  runtime_version = "3.x.x"

[[analyzers]]
name = "sql"

[[analyzers]]
name = "php"

[[analyzers]]
name = "javascript"

[[analyzers]]
name = "docker"

[[analyzers]]
name = "java"

  [analyzers.meta]
  runtime_version = "11"

[[analyzers]]
name = "go"

  [analyzers.meta]
  import_root = "github.com/ivaanlc27/deepsource_tests"

[[analyzers]]
name = "cxx"

[[analyzers]]
name = "csharp"